name = "Cractorism"
author = "Kito"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cd494dff618f1744e6a3830cd3fb4ff9298fef97655069f38587c0dbd12a7ed"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
