name = "Cractorism"
author = "Kito"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa550c6ff5963c966289224788892e9142e1c71e6ca877918590a222acee131b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
