name = "Cractorism"
author = "Kito"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4b4d8a4ca40e17d320c25d29cadbe21a7613eb4f533a9755e6c057a7bf92710"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
