name = "Cractorism"
author = "Kito"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "326570e99eab1ffe3fcd4a66506dea73371e478f12a5782ee4790a96727168fb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
