name = "Cractorism"
author = "Kito"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "410879a3b26dce4aac3f18d907df1e52ec7c3f1cbac96af42e989e5726384a07"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
