name = "Cractorism"
author = "Kito"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa11c98d7d2b9b094bedb03918b281810dad7973c0e3f9e13cee3415fb2ab5b0"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
