name = "Cractorism"
author = "Kito"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1a90f9d0b279f86242fcdd0d876418cb14eb040786124f667d8b79981770b9b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
