name = "Cractorism"
author = "Kito"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42791fada02e4a72ef3aa4628820e1b5f748cf4a610e1329522ff451ec362dfd"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
