name = "Cractorism"
author = "Kito"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74a8633f2f92d6035037a328f7e709f0824dee335d8ca10c82d233b3f11d2b24"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
